/* SPDX-License-Identifier: GPL-2.0-or-later */
#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		KC_Q, KC_W, KC_E, KC_R, KC_T,
		TD(0), TD(1), TD(2), TD(3), LT(2, KC_G),
		KC_Z, KC_X, KC_C, KC_V, KC_B,
		KC_DEL, LT(1, KC_BSPC), LT(3, KC_SPC),
		KC_Y, KC_U, KC_I, KC_O, KC_P,
		LT(2, KC_H), TD(4), TD(5), TD(6), TD(7),
		KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
		LT(3, KC_ENT), LT(1, KC_TAB), KC_ESC
	),
	[1] = LAYOUT(
		KC_GRV, KC_QUOT, LSFT(KC_QUOT), LSFT(KC_4), LSFT(KC_1),
		TD(8), TD(9), TD(10), TD(11), LSFT(KC_DOT),
		LSFT(KC_GRV), LSFT(KC_3), LSFT(KC_6), LSFT(KC_7), KC_BSLS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		LSFT(KC_EQL), LSFT(KC_LBRC), LSFT(KC_RBRC), LSFT(KC_SLSH), KC_PAST,
		KC_PMNS, TD(12), TD(13), TD(14), TD(15),
		LSFT(KC_2), KC_LBRC, KC_RBRC, KC_PDOT, KC_PSLS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[2] = LAYOUT(
		KC_MUTE, KC_VOLD, KC_VOLU, KC_MPLY, KC_NO,
		KC_LSFT, KC_LOPT, KC_LCTL, KC_LSFT, KC_END,
		KC_NO, KC_NO, KC_MPRV, KC_MNXT, KC_NO,
		KC_APP, KC_WH_U, KC_WH_D,
		KC_NO, LSFT(KC_Y), KC_END, LSFT(KC_I), KC_NO,
		KC_HOME, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT,
		KC_NO, LSFT(KC_N), LSFT(KC_M), KC_NO, KC_NO,
		KC_PGDN, KC_PGUP, KC_END
	),
	[3] = LAYOUT(
		KC_F1, KC_F2, KC_F3, KC_F4, KC_HOME,
		TD(16), TD(17), TD(18), TD(19), KC_END,
		KC_F9, KC_F10, KC_F11, KC_F12, KC_CALC,
		KC_LSFT, KC_LCTL, KC_LOPT,
		LSFT(KC_EQL), KC_P7, KC_P8, KC_P9, KC_PAST,
		KC_PMNS, TD(20), TD(21), TD(22), TD(23),
		KC_P0, KC_P1, KC_P2, KC_P3, KC_PSLS,
		KC_RALT, KC_P0, KC_PDOT
	),
	[4] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[5] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[6] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[7] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[8] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[9] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	)
};
